### PR TITLE
[205] Fix representations representation refresh

### PR DESCRIPTION
**Pull request by RaphaelPageObeo**
Bug: #205
Signed-off-by: Raphaël Pagé <raphael.page@obeo.fr>

### CODE REVIEW

**Comment by RaphaelPageObeo** [comment]
I am not sure why the eca check is failing. When I go on my profile, it says that it is still valid : 
image
image

**Comment by pcdavid** [comment]
@RaphaelPageObeo Is your GitHub account configured in your Eclipse profile? It's often the cause of such errors.

**Review by pcdavid — APPROVED** [review]

**Comment by RaphaelPageObeo** [comment]
It fixed itself :D

**Review by gcoutable — CHANGES_REQUESTED** [review]
The commit and PR title should refer to [205]

**Review by gcoutable — APPROVED** [review]

**Pull request merged**
