### PR TITLE
[releng] Stop minifying the code for Sirius Components packages

### PR DESCRIPTION
**Pull request by sbegaudeau**
Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by pcdavid** [comment]
I'm still seeing some components' names minified (though much less than before), not sure if this is normal or not:

The Explorer before:

screenshot-2023-06-09_11-42

The Explorer after:

screenshot-2023-06-09_11-42_1

Actual Mui component's names, but not sure what the "At", "Ce", "Dt" correspond to.

Similar names ("Wr", "Vs", "ys", "ke"...) in the details view:

screenshot-2023-06-09_11-44

**Comment by pcdavid** [comment]
I assume this would solve #831 and #1429?

**Comment by sbegaudeau** [comment]
- I had an issue removing the magnification with Sirius Web code, I only did it for Sirius Components code.
- It may not solve either of those issues. For the first one, we could pretty much stop minifying anything except in Sirius Web. Since we are publishing a library, our consumers can use a minified on their side. No real need to minify twice. The second issue is linked to the ability to edit some code in sirius-components-forms and see the frontend be reloaded automatically, I did not try to solve this issue here.

I could update my PR to remove minification from every frontend packages from Sirius Components, what do you think? It would make it easier for everybody (I'll just have to test that Sirius Web minifies the code properly as expected.

**Comment by gcoutable** [comment]
I don't understand well what will result from such configuration in production mode, do all components from `sirius-components` be minified?

**Comment by sbegaudeau** [comment]
> I don't understand well what will result from such configuration in production mode, do all components from `sirius-components` be minified?

If the mode is not development then yes things would get minified. I'm more and more convinced that we shouldn't even do that and instead release non-minified bundles since developers end up minifying things in the end...

**Review by gcoutable — APPROVED** [review]

**Pull request merged**
