### PR TITLE
Fix coding rules test errors

### PR DESCRIPTION
**Pull request by Gelio**
Fix all errors reported when running `mvn test`.

The errors were reported in 2 batches. The first batch:

```sh
$ ./mwnv clean test
[ERROR] Tests run: 6, Failures: 2, Errors: 1, Skipped: 0, Time elapsed: 0.061 s <<< FAILURE! - in org.eclipse.sirius.web.services.architecture.ImmutableTests
[ERROR] immutableClassesShouldHaveAPrivateConstructor  Time elapsed: 0.022 s  <<< FAILURE!
java.lang.AssertionError:
Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.eclipse.sirius.web.services..' and are annotated with @Immutable and are not annotated with @GraphQLInputObjectType should have only private constructors' was violated (2 times):
Constructor <org.eclipse.sirius.web.services.api.projects.UnzippedProject.<init>()> is not private in (UnzippedProject.java:31)
Constructor <org.eclipse.sirius.web.services.api.representations.RepresentationDescriptor.<init>()> is not private in (RepresentationDescriptor.java:27)

[ERROR] immutableClassesShouldBeFinal  Time elapsed: 0.005 s  <<< FAILURE!
java.lang.AssertionError:
Architecture Violation [Priority: MEDIUM] - Rule 'classes that reside in a package 'org.eclipse.sirius.web.services..' and are annotated with @Immutable should have modifier FINAL' was violated (2 times):
Class <org.eclipse.sirius.web.services.api.projects.UnzippedProject> does not have modifier FINAL in (UnzippedProject.java:0)
Class <org.eclipse.sirius.web.services.api.representations.RepresentationDescriptor> does not have modifier FINAL in (RepresentationDescriptor.java:0)

[ERROR] immutableClassesShouldHaveANestedBuilder  Time elapsed: 0.007 s  <<< ERROR!
java.lang.IllegalArgumentException: No field with name 'projectManifest in class org.eclipse.sirius.web.services.api.projects.UnzippedProject$Builder
```

The 2nd batch (related to the `projectManifest` field name) was reported after I fixed the first batch.

Surprisingly, those errors are not reported when running `mvn verify`. I could not find out why.

Related to https://github.com/Gelio/CAL-web/issues/62

### CODE REVIEW

**Comment by Gelio** [comment]
I have signed the Eclipse Contributor Agreement 3.1.0. Let me know if I should put the _Signed-off-by_ field in the footer of the commit message.

**Comment by pcdavid** [comment]
> I have signed the Eclipse Contributor Agreement 3.1.0. Let me know if I should put the _Signed-off-by_ field in the footer of the commit message.

I believe this is not needed anymore since https://bugs.eclipse.org/bugs/show_bug.cgi?id=558653.

**Review by pcdavid — APPROVED** [review]
Thanks for the contribution!

I will just update the commit message to start with `[test]` to follow our conventions, and I'd like the understand what causes the behavior difference between `tesŧ` and `verify` before closing this.

My understanding, confirmed by https://stackoverflow.com/questions/66876221/what-is-the-difference-between-mvn-verify-vs-mvn-test for example, is that `verify` "includes" `test`, and indeed when I run `mvn clean verify` I get a surefire report for `ImmutableTests`:

```
-------------------------------------------------------------------------------
Test set: org.eclipse.sirius.web.services.architecture.ImmutableTests
-------------------------------------------------------------------------------
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.56 s - in org.eclipse.sirius.web.services.architecture.ImmutableTests
```

So they *are* executed.

This happens on ArchUnit tests whose "body" is actually inherited and defined in another project, so maybe some differences in how the classpath is setup makes ArchUnit not see the same classes to check for?

**Comment by pcdavid** [comment]
Instrumenting `ImmutableTests.getClasses()` confirms that ArchUnit does not see the same classes to check for between `test` and `verify`:
* `mvn clean test`: ImmutableTests.getClasses() found 89 classes
* `mvn clean verify`: ImmutableTests.getClasses() found 48 classes

**Comment by Gelio** [comment]
Thanks for the comments and the investigation! I have updated the commit title so it begins with `[test]`, as you asked.

I am not well versed in Java and its ecosystem, so I don't know how I can help debug the problem further, unfortunately

**Review by sbegaudeau — DISMISSED** [review]
Could you add `Signed-off-by: FirstName LastName <email>` as the last line of your commit message please? While it's not required anymore by the Eclipse Foundation itself, we are still using it.

**Comment by Gelio** [comment]
Sure thing, I've just added that footer to the commit message and rebase on the latest `master`.

**Comment by pcdavid** [comment]
I've merged this even though for the moment I do not have a solution to get ArchUnit to see the expected classes when using the `verify` goal. I'll try to investigate this later.

**Pull request merged**
