### PR TITLE
[cleanup] fix local variable naming

### PR DESCRIPTION
**Pull request by Koi-tsk**
Signed-off-by: Koi-tsk <337023856@qq.com>

### CODE REVIEW

**Review by pcdavid — APPROVED** [review]
Thanks. Could you just add a `[cleanup]` prefix to your commit message to follow our conventions?

**Comment by Koi-tsk** [comment]
> Thanks. Could you just add a `[cleanup]` prefix to your commit message to follow our conventions?

done

**Review by pcdavid — APPROVED** [review]

**Comment by pcdavid** [comment]
> > Thanks. Could you just add a `[cleanup]` prefix to your commit message to follow our conventions?
> 
> done

You changed the PR title, but that is different from the commit message (which is the one that will end up in our commit history).
I'll make the change myself, no need for another round trip.

**Comment by pcdavid** [comment]
Actually I can't, as the commit is in your own fork...

**Comment by Koi-tsk** [comment]
> Actually I can't, as the commit is in your own fork...

Sorry, i got it wrong,is it right now?

**Comment by sbegaudeau** [comment]
@pcdavid I'm pretty sure that you can change the commit even in someone's fork, I do it all the time with other contributors.

**Comment by sbegaudeau** [comment]
@pcdavid and to confirmed it, I've just fix a small issue in the commit message. If a person forks sirius-web on Github, you automatically become contributor of said fork.

**Pull request merged**
