### PR TITLE
[1448] Make AddWidgetEventHandler less dependent on naming conventions

### LINKED ISSUE #1448: Textarea widgets created from the Form Description Editor do not have a default style
In the Form Description editor, creating a new widget by DnD from the sidebar normally creates a widget and its corresponding default style.
This is not the case for _TextArea_ widgets.
This is due to `AddWidgetEventHandler.createStyle(WidgetDescription)` which tries to create the style instance reflexively using assumptions on the name of the style which does not hold for _Text Areas_:
```java
widgetDescription.eClass().getName() + "Style"
```
In the case of the _Text Area_, the names are `TextAreaDescription` and `TextareaDescriptionStyle` (note the `A` _vs_ `a`).

### PR DESCRIPTION
**Pull request by pcdavid**
Bug: https://github.com/eclipse-sirius/sirius-components/issues/1448
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by pcdavid** [comment]
This fixes the issue, but still relies on "magic" assumptions regarding how the metamodel elements are named.
It seems a more robust approach would be for `AddWidgetInput.kind` to correspond to a possible `childCreationDescriptionId` as expected by `IEditService.createChild(IEditingContext, Object, String)`, and call that directly to create the whole widget, with any default values/children as may be customized in `FormDescriptionItemProvider.collectNewChildDescriptors(Collection<Object>, Object)`.

**Review by AxelRICHARD — APPROVED** [review]

**Comment by AxelRICHARD** [comment]
@pcdavid thank you!
@sbegaudeau it's ok on my side. Could you review and merge, please?

**Comment by AxelRICHARD** [comment]
@pcdavid could you rebase the PR to avoid conflicts please?

**Comment by pcdavid** [comment]
> @pcdavid could you rebase the PR to avoid conflicts please?

Done.

**Pull request merged**
